# ECI 153 Lab3 Python Introduction

## Python Download

### 1. Downloading and Installing Anaconda

(Skip this step if you know how to use Jupyter notebook and install packages)

Anaconda is a popular distribution of Python that includes many additional libraries and tools, making it ideal for scientific computing, data science, and machine learning.

Steps:
1. Go to the Anaconda Website: Go to the Anaconda download page at Anaconda's official site https://www.anaconda.com/download/success 
2. Download the Installer: Select the installer that matches your operating system (Windows, macOS, or Linux). 
3. Install Anaconda: Run the downloaded installer.

### 2. Using Jupyter Notebook
Jupyter Notebook is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations, and narrative text. (This page is written in jupyter notebook)


To launch Jupyter Notebook: From **Anaconda Navigator**, launch **Jupyter Notebook**. This will open Jupyter in your default web browser.
Create a New Notebook: In the Jupyter Notebook interface, click on “New” at the top right corner, and then select “Python 3” to start a new notebook.

We can write equations using latex: 
$$
\min z= \sum_{i=1}^N c_i x_i 
$$



You can enter Python code in the cells. To execute the code in a cell, press **Shift + Enter**.
Adding More Cells: You can add more cells by clicking on the “+” button on the toolbar or using the insert menu.

In Python, `#` is used to comment a line of code. What follows after `#` will not be evaluated.

In [2]:
# assign value 1 to variable a
a = 1
# assign the value of (a+1) to variable a
a = a+1

In [3]:
print(a)

2


In [ ]:
# It is possible that you do not execute the cell
# In this case, there will no output
a = 10
print(a)

In [4]:
# a is still 2, since the above cell was not executed 
print(a)

2


Executed cells have a number in the `[]`. It records the **order** to run the cells. The order matters!


### 3. Python 101

In [11]:
# assignment 
# syntax: Var = value

# data types

# numeric
a = 2024

# string 
string = "ECI 153"
print(string, a)

# complicated data types
# list
# list can be defined in two ways, using list(), or simply []
list1 = list([1, 2, 3, 4])
print(list1)

# add one element to the list
list1.append(5)  
print(list1)

# list of lists
# define list using []
list2 = [[1, 2], [3, 4]]
print(list2)

ECI 153 2024
[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[[1, 2], [3, 4]]


In python, **the index starts from 0**. The first element of a list is `list1[0]`.

In [20]:
list1[0]

1

In [23]:
# the 5th element is indexed 3!!
list1[4]

5

In [24]:
# a length-5 list can only have index 0,1,2,3,4
# it will give you an error if the index is out the range
list1[5]

IndexError: list index out of range

There are many in-built functions in Python. 

In [14]:
 # minimum value from a list
min(list1)

1

In [25]:
sum(list1)

15

#### If statement
In Python, the `if` statement is used for conditional execution. It allows you to execute a block of code only if a certain condition is true. Here's the basic syntax:


In [30]:
if 5>4: 
    print("5 is greater than 4")
    print("this line will also be executed")

5 is greater than 4
this line will also be executed


In [32]:
if 3>4: 
    print("3 is greater than 4")
    print("IF statement is true")
else: 
    print("3 is less than 4")
    print("IF statement is false")


3 is less than 4
IF statement is false




Unlike many other programming languages that use braces `{}` or keywords like `begin` and `end` to denote blocks of code, Python uses indentation (press TAB) to indicate the beginning and end of code blocks.

#### Loops



In [28]:
# range generate a sequence of number (it does not contain 5)
for i in range(5):
    print(i)

0
1
2
3
4


In [34]:
i = 0
while i < 5:
    print(i)
    i = i + 1

0
1
2
3
4


#### User-defined functions

In [36]:
def get_the_min_max(l):
    return min(l), max(l)

l = [4, 10, 3, -1, 22]
l_min, l_max = get_the_min_max(l)

In [38]:
l_min, l_max

(-1, 22)

### 4. Import Packages

Like any open-source languages, Python supoort many packages (libraries of code). You can use the code by importing the module. 

1. Importing a module from a package
`import package_name.module_name`

1. Importing a module from a package with an alias
`import package_name.module_name as alias`

There are packages that is downloaded already, like `numpy`. However, there are also packages that are not by default downloaded, and installation is needed before you can access those.

In [1]:
# this is a library that we can directly import
# NumPy is a fundamental package for scientific computing in Python. I
import numpy 

In [3]:
# numpy.array() is a function that create 
array_a = numpy.array([1, 0, 0, 0])
print(array_a)

[1 0 0 0]


In [4]:
# we often want alias to make the code easy to read
import numpy as np
print(np.array([1, 0, 0, 0]))

[1 0 0 0]


In [55]:
# the index of numpy array starts from 0 too
array_a[0]

1

In [6]:
# elementwise addition
array_a + 10 

array([11, 10, 10, 10])

In [60]:
# numpy array is the python way to define matrices and vectors

A = np.array([[1, 0], [0, 1]])
B = np.array([[1, 1], [1, 1]])
x = np.array([10, 5])

# Perform matrix multiplication using the @ operator or np.dot()
Ax = A @ x  # Alternatively, you can use np.dot(A, B)
Ax

array([10,  5])

In [61]:
Bx = B @ x
Bx

array([15, 15])

In [62]:
# also, the index of 2D numpy array starts from 0
# the following gives the first row of the matrix
A[0]

array([1, 0])

In [63]:
# to get the first element (1-st row, 1-st column)
A[0, 0]

1

#### 4. Package that Solves Linear Programming

There are many python packages that can solve LPs. Today, we will only learn to use the in-built package `SciPy`. 

Consider the problem 
$$ \max x_1+2x_2 $$
$$  x_1+3x_2 \leq 8$$
$$  x_1+x_2 \leq 4$$
$$  x_1,x_2 \geq 0$$

Equivalently (objective function changed to **minimize** because scipy deals with minimization problem): 
$$ \min -x_1-2x_2 $$
$$  x_1+3x_2+s_1 = 8$$
$$  x_1+x_2 +s_2 =4$$
$$  x_1,x_2,s_1,s_2 \geq 0$$

When reporting final objective value, remember to report the negative of it.


In [52]:
from scipy.optimize import linprog

# Objective function coefficients
c = [-1, -2, 0, 0]  # Maximize z = x + 2y  = Minimize -x-2y

# Coefficients of inequality constraints (left-hand side of inequalities)
A = [[1, 3, 1, 0], [1, 1, 0, 1]]  # x1 + 3x2 + s1 = 8, x1 + x2 + s4 = 4

# Right-hand side of inequality constraints
b = [8, 4]

# Solve linear programming problem
res = linprog(c, A_eq=A, b_eq=b)

print("Optimal values:", res.x)
print("Optimal cost:", -res.fun) # Note the negative sign to get the maximized value

Optimal values: [2.00000000e+00 2.00000000e+00 4.45649626e-11 3.55752376e-13]
Optimal cost: 5.999999999955222


In [53]:
# use function round() to round the floating point number to 2 digits after the decimal point
print("Optimal values:", res.x.round(2))
print("Optimal cost:", -res.fun.round(2))

Optimal values: [2. 2. 0. 0.]
Optimal cost: 6.0
